# Generated by Django 5.1 on 2024-08-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('correspondance', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ListInterco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interco', models.CharField(max_length=10, unique=True)),
                ('societe1', models.CharField(blank=True, max_length=150)),
                ('ecpiece_tableau_1', models.CharField(blank=True, max_length=15)),
                ('societe2', models.CharField(blank=True, max_length=150)),
                ('ecpiece_tableau_2', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom du Société')),
                ('user', models.CharField(default='reader', max_length=150)),
                ('password', models.CharField(default='m1234', max_length=150)),
                ('server', models.CharField(max_length=25)),
                ('types', models.CharField(choices=[('sage100', 'Sage100'), ('x3v1', 'X3V1(AGRI)'), ('x3v2', 'X3V2(SMTP)')], max_length=50)),
                ('value', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'active'],
            },
        ),
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(blank=True, max_length=50)),
                ('ecPiece', models.IntegerField()),
                ('ecRefPiece', models.CharField(max_length=50)),
                ('ecNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntercoHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interco', models.CharField(blank=True, max_length=10)),
                ('tableau1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_tableau1', to='home.tableau')),
                ('tableau2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_tableau2', to='home.tableau')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societe1_associations', to='home.societe', verbose_name='Societe 1')),
                ('societe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societe2_associations', to='home.societe', verbose_name='Societe 2')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tiers', verbose_name='Numéro Tiers')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.type', verbose_name='Type de Transaction')),
            ],
        ),
    ]
