# Generated by Django 5.1.1 on 2024-09-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_societe_created_at_alter_societe_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiers',
            new_name='Tier',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tiers',
            new_name='tier',
        ),
        migrations.RemoveField(
            model_name='associationsociete',
            name='tiers',
        ),
        migrations.AddField(
            model_name='associationsociete',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tier', verbose_name='Numéro Tier'),
        ),
    ]
