# Generated by Django 5.1.1 on 2024-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_tiers_tier_rename_tiers_transaction_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(max_length=255)),
                ('codetiers', models.CharField(max_length=255)),
                ('intitule', models.CharField(max_length=255)),
                ('tiers', models.CharField(max_length=255)),
                ('comptegeneral', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tier',
            name='value',
        ),
        migrations.AddField(
            model_name='tier',
            name='societe',
            field=models.CharField(default='Default', max_length=255),
        ),
    ]
